### ISSUE TITLE
input="file" stops the parsing chain if it doesn't have a name

### ISSUE THREAD

**Issue by laddi-netapp** [runarberg/formsquare#21]
Create a form with several elements.  Add a name attribute for all of them and then place an input="file" somewhere inside the form.  When you then parse you will get back an array with the first item as the Object parsed name attributes and then a promise for the file input.  But the object will only contain the values for the elements before the file input, not the ones following it.

**Comment by runarberg** [comment]
@laddi-netapp  can you provide an example form, e.g.:

```html
<form>
  <input type="text">
  <input type="file">
  <button>Submit</button>
</form>
```

**Comment by laddi-netapp** [comment]
```
<form>
   <input type="text" name="foo" value="xxx" />
   <input type="file" />
   <input type="text" name="bar" value="yyy" />
</form>
```

What will happen is that on parsing you will get an `Array` back with two items:
`[{ foo: 'xxx' }, promise]`

But `bar: 'yyy'` will be omitted...

**Comment by runarberg** [comment]
@laddi-netapp It looks likes the `type="file"` is not the issue here. This can be reproduced with:

```html
<form>
  <input type="text" name="foo" value="xxx" />
  <input type="text" value="bar" />
  <input type="text" name="baz" value="yyy" />
</form>
```
You will get back a two element array with an additional attribute `bar`:

```js
const values = formsquare(document.forms[0]);

console.log(values);
// => [{ foo: "xxx" }, "bar"]

console.log(values.baz);
// => "baz"
```

So the problem is if you have an unnamed field sandwiched between named fields. The unnamed field will make an array of the already passed fields plus the value of the value of the current field. After that every named field will be added as an attribute to the array.

I’m not really sure what behavior we should expect from this situation as the [abandoned spec draft](https://www.w3.org/TR/html-json-forms/) never addressed that.

**Comment by runarberg** [comment]
I think it would make the most sense to not convert the previous values into an array and simply add the current index as a key to the existing object. This however will not fix the case of the first field being unnamed followed by at least one named field.
